### ISSUE TITLE
Exclude bootstrap user from Access Certification CSV export

### ISSUE THREAD

**Issue by lszenten** [OneIdentity/safeguard-ps#132]
The bootstrap user cannot be added to groups nor included in policy.  It doesn't represent a person and likely won't have the required fields for importing into Access Certification.

Please enhance the scripts to prevent the bootstrap user from being included in the CSV export.

**Comment by petrsnd** [comment]
Fixed by #135 
Added a condition to include all internal users
Will be in safeguard-ps 2.7.  Could be backported easily if needed.
