### ISSUE TITLE
Update-Module documentation may be incorrect

### ISSUE THREAD

**Issue by simonvane** [OneIdentity/safeguard-ps#133]
Running the following as stated in the read me:
`Update-Module safeguard-ps -Scope CurrentUser -Verbose`

Results in the following error:
```
Update-Module : A parameter cannot be found that matches parameter name 'Scope'.
At line:1 char:28
+ Update-Module safeguard-ps -Scope CurrentUser -Verbose
+                            ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Update-Module], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Update-Module
```
Running the following succeeds:
`Update-Module safeguard-ps -Verbose`

**Comment by simonvane** [comment]
I've realised my mistake, you can install for the first time with Update-Module as described. It might just be worth removing the `Update-Module safeguard-ps -Scope CurrentUser -Verbose` install case to avoid confusion?

**Comment by petrsnd** [comment]
Yeah.  Maybe I can remove that and just leave it for the `Install-Module` case.  I wanted to have an option up there for people who may not have Administrator on their box.  Do you know if `Update-Module` will always update the appropriate original scope according to the initial install without the `-Scope` parameter?

**Comment by simonvane** [comment]
Good question but I'm afraid I don't know. I can't find how to determine the scope a module is installed for.  `Get-InstalledModule safeguard-ps` does not return that info and my google foo is failing me.

Having said that, when I run `Update-Module safeguard-ps` in a PowerShell console running as administrator the module remains in `$env:USERPROFILE\Documents\WindowsPowerShell\Modules` and doesn't move to `$env:ProgramFiles\WindowsPowerShell\Scripts` or `$env:ProgramFiles\PowerShell\Modules` (mentioned here https://docs.microsoft.com/en-us/powershell/module/powershellget/install-module?view=powershell-6#notes and here https://docs.microsoft.com/en-us/powershell/gallery/getting-started#install).

The only think I'm not clear on is whether behaviour would have been different if I wasn't already on the latest version.

**Comment by petrsnd** [comment]
I'll look for a machine where I've installed it as the current user, and I'm not on the latest.  My problem is that I almost always install it for all users as an Administrator.

**Comment by simonvane** [comment]
Thank you.

**Comment by petrsnd** [comment]
I improved the documentation PR #141.  Hopefully it keeps people on the right track now between installing as admin for the machine vs as single user.

**Comment by simonvane** [comment]
Thanks Dan.
