### ISSUE TITLE
Can't create a new access request

### ISSUE THREAD

**Issue by bnicholesdell** [OneIdentity/safeguard-ps#170]
All of the following commands fail:

New-SafeguardAccessRequest "Linux Server" "pluto" SSH 
New-SafeguardAccessRequest 13 6 SSH 
New-SafeguardAccessRequest -AssetToUse 13 -AccountToUse 6 -AccessRequestType SSH 
New-SafeguardAccessRequest -AssetToUse "Linux Server" -AccountToUse "pluto" -AccessRequestType SSH 

I have verified that the asset and account exist with the corresponding names and ids.  Showing the debug output produces the same error for all of the commands.  The JSON payload that is produced by the cmdlet is:

{
    "AccessRequestType":  "SSH",
    "SystemId":  13
}

The above JSON is always missing the AccountId.  Using the same JSON and calling the REST interface directly produces the same error.  However, adding the AccountId to the JSON and calling the REST interface, works.  The error that is produced is:

VERBOSE: ---Response Status---
VERBOSE: 403 Forbidden
VERBOSE: ---Response Body---
VERBOSE: {"Code":90408,"Message":"You are not authorized to use this request type for this request.","InnerError":null}
VERBOSE: ---Exception---
VERBOSE:

Status         : ProtocolError
Response       : System.Net.HttpWebResponse
Message        : The remote server returned an error: (403) Forbidden.
Data           : {}
InnerException :
TargetSite     : System.Net.WebResponse GetResponse(System.Net.WebRequest)
StackTrace     :    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
                    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
HelpLink       :
Source         : Microsoft.PowerShell.Commands.Utility
HResult        : -2146233079

**Comment by Goelrachit** [comment]
@bnicholesdell @DanPeterson We pass in AccountId only for "Password" type AccessRequestType. There is a comment in the code that says "Accounts are required for password requests, but not for sessions where you can use bring your own account". I believe the "RemoteDesktop" and "RDP" AccessRequestType(s) are for sessions. 

Does "Ssh" type also falls under sessions? 

Is "AccountId" is a required parameter for "Ssh" type access request?

**Comment by bnicholesdell** [comment]
Yes.  SSH AccessRequestType is for sessions as well.

**Comment by Goelrachit** [comment]
@bnicholesdell I opened a PR for this. I think we can try to resolve the AccountID even if the AccessRequestType is not "Password", but "AccountToUse" is provided.

You can test the code change with the safeguard-ps attached. It's a copy of the package from my branch. I don't have a sessions environment set up to test this completely.

[safeguard-ps.zip](https://github.com/OneIdentity/safeguard-ps/files/3561664/safeguard-ps.zip)

**Comment by bnicholesdell** [comment]
@Goelrachit This seems to work as expected now.  I was able to create an access request using the account, asset and SSH type.

**Comment by petrsnd** [comment]
@bnicholesdell 

Can you verify that your test cases work now with 2.9.357-pre?
