### ISSUE TITLE
Enhancement Request: $SafeguardSession

### ISSUE THREAD

**Issue by Eric2XU** [OneIdentity/safeguard-ps#174]
I mentioned this in my other post about connect-safeguard but this should really be a PSObject not a Hashtable. Personally I think as long as an object can be returned by $ymvar = connect-safeguard then you dont have to go back and retool. 

More importantly both the main $safeguardSession and any returned var needs to have a token expire date time so I can write code to redo auth when expired instead of having to guess and/or authenticate each time.

**Comment by petrsnd** [comment]
@Eric2XU 

The hashtable is really meant to be internal.  It isn't meant to be used or manipulated by the end user.  It is an internal connection context.  I mentioned in the other issue that I'd like to understand your use case and whether or not you've considered using the `-NoSessionVariable` parameter.

Right now you can do what you want using the `Get-SafeguardAccessTokenStatus` and `Update-SafeguardAccessToken` cmdlets.

```PowerShell
PS> $AccessToken = (Connect-Safeguard -Insecure sg-hw.dan.vas local Matt -NoSessionVariable)
Password: ********
PS> Get-SafeguardAccessTokenStatus -Appliance sg-hw.dan.vas -Insecure -AccessToken $AccessToken
Token lifetime remaining: 23 hours 47 minutes
PS> Get-SafeguardAccessTokenStatus -Appliance sg-hw.dan.vas -Insecure -AccessToken $AccessToken -Raw

Days              : 0
Hours             : 23
Minutes           : 47
Seconds           : 0
Milliseconds      : 0
Ticks             : 856200000000
TotalDays         : 0.990972222222222
TotalHours        : 23.7833333333333
TotalMinutes      : 1427
TotalSeconds      : 85620
TotalMilliseconds : 85620000
```

You can just call `Connect-Safeguard` with the `-NoSessionVariable` parameter to refresh your token.

These cmdlets also work with the $SafeguardSession variable internally and you don't have to specify any parameters to use `Update-SafeguardAccessToken`.

**Comment by Eric2XU** [comment]
outstanding! Thanks for the info, I do recommend you updated the readme to reflect this information.
