### ISSUE TITLE
403: Forbidden -- 60108: Authorization is required for this request.

### ISSUE THREAD

**Issue by Eric2XU** [OneIdentity/safeguard-ps#175]
I am unable to retrieve accounts from Safeguard using these powershell commands. 

`Get-SafeguardAssetAccount -AccessToken $SGS.AccessToken -Appliance $SafeguardIP -Insecure  -AccountToGet $a -AssetToGet "My Directory"`

`Get-SafeguardDirectoryAccount -AccessToken $SGS.AccessToken -Appliance $SafeguardIP -Insecure -AccountToGet $a -DirectoryToGet "My Directory"`

I have tired both with and without providing the token. (Don't be alarmed by the SGS.AccessToken, I just convert your $SafeguardSession hashtable to a PSObject). 

To confirm, the account I am logging into safeguard with can check out the requested account via the web portal.  I am also unclear which cmdlet to use which is why I tried both.

**Comment by petrsnd** [comment]
403 forbidden means that you do not have the appropriate permissions to request the asset accounts resource.  The user that you are using to authenticate just doesn't have the right permissions.

It isn't actually recommended to convert the $SafeguardSession internal variable to a PSObject.  

Below is an example of me performing your same use case where the user has the correct permissions.  Notice the use of the `-NoSessionVariable` parameter.

```PowerShell
PS> $AccessToken = (Connect-Safeguard -Insecure sg-hw.dan.vas local Matt -NoSessionVariable)
Password: ********
PS> Get-SafeguardAssetAccount -AccessToken $AccessToken -Appliance sg-hw.dan.vas -Insecure -AssetToGet linux.dan.vas -AccountToGet root

Id                            : 1
Name                          : root
DistinguishedName             :
DomainName                    :
Description                   :
SystemId                      : 1
AllowPasswordRequest          : True
AllowSessionRequest           : True
PlatformId                    : 188
PlatformType                  : Ubuntu
PlatformDisplayName           : Ubuntu Other
IsAcctNameCaseSensitive       : True
PlatformFamily                : Linux
HasPassword                   : True
HasAccountTaskFailure         : False
LastPasswordCheckDate         : 2019-07-31T19:36:10.956Z
LastSuccessPasswordCheckDate  : 2019-07-31T19:36:10.956Z
LastFailurePasswordCheckDate  :
LastPasswordCheckTaskId       : 7321c78a-b3ca-11e9-b4b1-ebaa869b3e6e
FailedPasswordCheckAttempts   : 0
LastPasswordChangeDate        : 2019-08-19T14:54:26.349Z
LastSuccessPasswordChangeDate : 2019-08-19T14:54:26.349Z
LastFailurePasswordChangeDate :
LastPasswordChangeTaskId      :
FailedPasswordChangeAttempts  : 0
LastSshKeyChangeDate          :
LastSuccessSshKeyChangeDate   :
LastFailureSshKeyChangeDate   :
LastSshKeyChangeTaskId        :
FailedSshKeyChangeAttempts    : 0
LastSuspendAccountDate        :
LastSuccessSuspendAccountDate :
LastFailureSuspendAccountDate :
LastSuspendAccountTaskId      :
FailedSuspendAccountAttempts  : 0
LastRestoreAccountDate        :
LastSuccessRestoreAccountDate :
LastFailureRestoreAccountDate :
LastRestoreAccountTaskId      :
FailedRestoreAccountAttempts  : 0
NextPasswordCheckDate         :
NextPasswordChangeDate        :
NextSshKeyChangeDate          :
NextSuspendAccountDate        :
NextRestoreAccountDate        :
AssetId                       : 1
AssetName                     : linux.dan.vas
AssetPartitionId              : -1
AssetPartitionName            : Macrocosm
CreatedDate                   : 2019-07-31T19:36:00Z
CreatedByUserId               : 1
CreatedByUserDisplayName      : Matt
SyncGroupId                   :
SyncGroupName                 :
SyncGroupPriority             :
Owners                        : {}
ProfileId                     :
ProfileName                   :
EffectiveProfileId            : -1
EffectiveProfileName          : Macrocosm Profile
Disabled                      : False
IsServiceAccount              : True
SharedServiceAccount          : False
Tags                          : {}
DiscoveredProperties          : @{AccountDiscoveryScheduleId=; AccountDiscoveryScheduleName=; DiscoveredUserId=; DiscoveredDate=;
                                DiscoveredGroups=System.Object[]}
DirectoryProperties           : @{NetbiosName=; ObjectGuid=; ObjectSid=}
```

**Comment by Eric2XU** [comment]
Can you please help me understand what additional permissions I need? As I explained I can check out these accounts via the Safeguard Web UI, why can I not check them out via PowerShell cmdlets? I did convert to pulling the token and using it but that has not changed the outcome

**Comment by Eric2XU** [comment]
I was able to figure this out, wrong cmdlet. I needed to use things like: 

`New-SafeguardAccessRequest -AccessToken $SGToken -Appliance $SafeguardIP -Insecure -AssetToUse “My Directory" -AccessRequestType "Password" -AccountToUse $a`

Although if already checked out it errors out instead of giving me the current access request.

**Comment by petrsnd** [comment]
@Eric2XU `New-SafeguardAccessRequest` will always create a new access request according to the proper use of PowerShell verbs.  `Get-SafeguardAccessRequest` will get existing access requests... however, if you want to get access requests corresponding to the currently logged in user, then you should actually use `Get-SafeguardActionableRequest -RequestRole Requester`.  This will return any of the access requests that you can manipulate as the requester.

This cmdlets correspond to the Safeguard API.  You can see the swagger at:
https://your.sg.appliance/service/core/swagger/ui/index#/

if you need more information
