### ISSUE TITLE
Exception still thrown when "-ErrorAction SilentlyContinue" is used with get-SafeguardApplianceState (and other commandlets

### ISSUE THREAD

**Issue by MikeFassbinder** [OneIdentity/safeguard-ps#176]
PS C:\Users\buildagent\desktop> get-SafeguardApplianceState -Insecure 192.168.0.105 -ErrorAction SilentlyContinue
503: Service Unavailable -- 0:
At C:\Program Files\WindowsPowerShell\Modules\safeguard-ps\2.8.349\sg-utilities.psm1:122 char:5
+     throw $local:ExceptionToThrow
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], SafeguardMethodException
    + FullyQualifiedErrorId : 503: Service Unavailable -- 0:

**Comment by Eric2XU** [comment]
I had noticed this too, when something fails it throws causing the entire script to handle. Not sure if this was by design but its unexpected in the automation world. Better to write through Error Actions.

**Comment by petrsnd** [comment]
This is a good enhancement request.

@Eric2XU For now, the workaround is to use try-catch blocks in your scripts.

**Comment by petrsnd** [comment]
@MikeFassbinder After looking into this further we use `throw` almost everywhere which generates a terminating error no matter what you do with how you set the `-ErrorAction` parameter.  We would have to change to use Write-Error everywhere.  This might be a bigger change than we want to attempt right now.

**Comment by Eric2XU** [comment]
Confucius quoted: “It does not matter how slowly you go as long as you do not stop”.

This is fairly fundamental and needs to be fixed. It may not be the most urgent thing to be worked on but it does need to be worked on eventually. I just hope it is added to the road map and is given a planned date to be fixed even if that date is many months out.

**Comment by petrsnd** [comment]
@Eric2XU The problem isn't just as simple as changing `throw` statements to `Write-Error`.  The problem is that we use `try-catch-finally` logic quite extensively in core areas of the module.  Those constructs cannot easily (or safely) be converted to `Write-Error` without extensive changes to critical cmdlets like `Invoke-SafeguardMethod` and its constituent private functions.  In short, it would be good to get comfortable with the `try-catch` workaround.

**Comment by petrsnd** [comment]
safeguard-ps uses throw semantics.  This will not be changed.  There is too much logic depending on it built into too many cmdlets.  Use `try-catch`.
