### ISSUE TITLE
Get-SafeguardAccessRequest Pipeline Issue

### ISSUE THREAD

**Issue by Eric2XU** [OneIdentity/safeguard-ps#180]
When running this code: 

`Get-SafeguardAccessRequest -AccessToken $SGToken -Appliance $SafeguardIP -Insecure | measure-object`

It returns 1 record.... 

Running this:
`Get-SafeguardAccessRequest -AccessToken $SGToken -Appliance $SafeguardIP -Insecure | gm`

Shows this: 

>  TypeName: System.Object[]
> 
> Name           MemberType            Definition                                                         
> ----           ----------            ----------                                                         
> Count          AliasProperty         Count = Length                                                     
> Add            Method                int IList.Add(System.Object value)                                 
> Address        Method                System.Object&, mscorlib, Version=4.0.0.0, Culture=neutral, Publ...
> Clear          Method                void IList.Clear()                                                 
> Clone          Method                System.Object Clone(), System.Object ICloneable.Clone()            
> CompareTo      Method                int IStructuralComparable.CompareTo(System.Object other, System....
> Contains       Method                bool IList.Contains(System.Object value)                           
> CopyTo         Method                void CopyTo(array array, int index), void CopyTo(array array, lo...
> Equals         Method                bool Equals(System.Object obj), bool IStructuralEquatable.Equals...
> Get            Method                System.Object Get(int )                                            
> GetEnumerator  Method                System.Collections.IEnumerator GetEnumerator(), System.Collectio...
> GetHashCode    Method                int GetHashCode(), int IStructuralEquatable.GetHashCode(System.C...
> GetLength      Method                int GetLength(int dimension)                                       
> GetLongLength  Method                long GetLongLength(int dimension)                                  
> GetLowerBound  Method                int GetLowerBound(int dimension)                                   
> GetType        Method                type GetType()                                                     
> GetUpperBound  Method                int GetUpperBound(int dimension)                                   
> GetValue       Method                System.Object GetValue(Params int[] indices), System.Object GetV...
> IndexOf        Method                int IList.IndexOf(System.Object value)                             
> Initialize     Method                void Initialize()                                                  
> Insert         Method                void IList.Insert(int index, System.Object value)                  
> Remove         Method                void IList.Remove(System.Object value)                             
> RemoveAt       Method                void IList.RemoveAt(int index)                                     
> Set            Method                void Set(int , System.Object )                                     
> SetValue       Method                void SetValue(System.Object value, int index), void SetValue(Sys...
> ToString       Method                string ToString()                                                  
> Item           ParameterizedProperty System.Object IList.Item(int index) {get;set;}                     
> IsFixedSize    Property              bool IsFixedSize {get;}                                            
> IsReadOnly     Property              bool IsReadOnly {get;}                                             
> IsSynchronized Property              bool IsSynchronized {get;}                                         
> Length         Property              int Length {get;}                                                  
> LongLength     Property              long LongLength {get;}                                             
> Rank           Property              int Rank {get;}                                                    
> SyncRoot       Property              System.Object SyncRoot {get;}         

However if I save to a var
`$test = Get-SafeguardAccessRequest -AccessToken $SGToken -Appliance $SafeguardIP -Insecure`

Then do 
`$test | gm `

I get back a proper object that includes the noteproperty's I was expecting: 

>    TypeName: System.Management.Automation.PSCustomObject
> 
> Name                        MemberType   Definition                                        
> ----                        ----------   ----------                                        
> Equals                      Method       bool Equals(System.Object obj)                    
> GetHashCode                 Method       int GetHashCode()                                 
> GetType                     Method       type GetType()                                    
> ToString                    Method       string ToString()                                 
> AccessRequestType           NoteProperty string AccessRequestType=Password                 
> AccountDomainName           NoteProperty string AccountDomainName=prod.quest.corp          
> AccountId                   NoteProperty int AccountId=6                                   
> AccountName                 NoteProperty string AccountName=PDA-EWeintra                   
> AccountRequestType          NoteProperty string AccountRequestType=LinkedPassword          
> AccountSystemId             NoteProperty int AccountSystemId=5                             
> AccountSystemName           NoteProperty string AccountSystemName=prod.quest.corp Directory
> AllowClipboard              NoteProperty bool AllowClipboard=False                         
> AllowScpSessions            NoteProperty bool AllowScpSessions=False                       
> AllowSessionPasswordRelease NoteProperty bool AllowSessionPasswordRelease=False            
> AllowSftpSessions           NoteProperty bool AllowSftpSessions=False                      
> AllowX11Forwarding          NoteProperty bool AllowX11Forwarding=False                     
> ApprovedByMe                NoteProperty bool ApprovedByMe=False                           
> AssetId                     NoteProperty int AssetId=5                                     
> AssetName                   NoteProperty string AssetName=prod.quest.corp Directory        
> AssetNetworkAddress         NoteProperty object AssetNetworkAddress=null                   
> CreatedOn                   NoteProperty string CreatedOn=2019-09-03T21:26:47Z             
> CurrentApprovalCount        NoteProperty int CurrentApprovalCount=0                        
> CurrentReviewerCount        NoteProperty int CurrentReviewerCount=0                        
> DurationInMinutes           NoteProperty int DurationInMinutes=600                         
> EnableCommandDetection      NoteProperty bool EnableCommandDetection=False                 
> EnableSessionRecordings     NoteProperty bool EnableSessionRecordings=False                
> ExpiresOn                   NoteProperty string ExpiresOn=2019-09-04T07:26:47Z             
> Id                          NoteProperty string Id=2987-1-AC1F6B75DB10-0242                
> IsEmergency                 NoteProperty bool IsEmergency=False                            
> NeedsAcknowledgement        NoteProperty bool NeedsAcknowledgement=False                   
> PolicyId                    NoteProperty int PolicyId=2                                    
> PolicyName                  NoteProperty string PolicyName=ADM Access Request Policy       
> ReasonCode                  NoteProperty object ReasonCode=null                            
> ReasonComment               NoteProperty object ReasonComment=null                         
> RequestAvailability         NoteProperty Object[] RequestAvailability=System.Object[]      
> RequestedDurationDays       NoteProperty int RequestedDurationDays=0                       
> RequestedDurationHours      NoteProperty int RequestedDurationHours=10                     
> RequestedDurationMinutes    NoteProperty int RequestedDurationMinutes=0                    
> RequestedFor                NoteProperty string RequestedFor=2019-09-03T21:26:47Z          
> RequesterDisplayName        NoteProperty string RequesterDisplayName=Eric Weintraub        
> RequesterEmailAddress       NoteProperty object RequesterEmailAddress=null                 
> RequesterId                 NoteProperty int RequesterId=1                                 
> RequiredApprovalCount       NoteProperty int RequiredApprovalCount=0                       
> RequiredReviewerCount       NoteProperty int RequiredReviewerCount=0                       
> RequireReviewerComment      NoteProperty bool RequireReviewerComment=False                 
> SessionConnectionPolicyRef  NoteProperty object SessionConnectionPolicyRef=null            
> SessionModuleConnectionId   NoteProperty object SessionModuleConnectionId=null             
> Sessions                    NoteProperty Object[] Sessions=System.Object[]                 
> State                       NoteProperty string State=PasswordCheckedOut                   
> StateChangedOn              NoteProperty string StateChangedOn=2019-09-03T21:26:56.5628897Z
> TicketNumber                NoteProperty object TicketNumber=null                          
> WasCancelled                NoteProperty bool WasCancelled=False                           
> WasCheckedOut               NoteProperty bool WasCheckedOut=True                           
> WasDenied                   NoteProperty bool WasDenied=False                              
> WasEvicted                  NoteProperty bool WasEvicted=False                             
> WasExpired                  NoteProperty bool WasExpired=False                             
> WasRevoked                  NoteProperty bool WasRevoked=False                             
> WorkflowActions             NoteProperty Object[] WorkflowActions=System.Object[]    

I have a feeling that the cmdlet needs improvement to pass data correctly to the pipeline. This effects all sorts of things like where, select, measure-object, etc... via the pipeline. While the workaround is simple (use a var) it should be corrected.

**Comment by petrsnd** [comment]
Hi Eric.  Thanks for the feedback.

`Get-SafeguardAccessRequest` returns the PowerShell result directly from `Invoke-RestMethod`, which returns an array, because that is what is generated from the REST API.

This is just how arrays work in PowerShell.  When fed to a pipeline, `Measure-Object` returns the number of elements in the array which is exactly what would be expected.  When fed to a pipeline, `Get-Member` returns the properties of the array object itself.

If you would like to have the objects enumerated through the pipeline, then you need to wrap the `Get-SafeguardAccessRequest` output in parenthesis so that it will be evaluated in the same way as an intermediate variable.  This will cause each of the constituent elements of the array to be passed to the pipeline instead of the array as a whole.  

To get what you're looking for use the following:
```PowerShell
PS> (Get-SafeguardAccessRequest) | Get-Member
```

`Measure-Object` is still going to tell you the number of elements in the array though--even with the parenthesis.  That's just how that cmdlet works.

**Comment by Eric2XU** [comment]
I guess we will have to agree to disagree. I think this is interpretive. PowerShell Committee Agreed that an RFC should be drafted to change the default behavior and add the option to revert for invoke-restmethod (and ConvertFrom-Json). Just not one has done it yet. So if people realize this isn't optimal, I would argue to you, that YOUR cmdlet works better with being able to use pipeline which means you should convert to object on the way out. But thank you for the workaround I will use that or stuffing vars moving forward.

**Comment by petrsnd** [comment]
@Eric2XU I think you're missing part of my point.  I'm just calling `Invoke-RestMethod`.  If Microsoft 'fixes' that to work the way you think it should, then you'll get your wish.  I don't expect it to change.

Glad the workaround works for you.
