### ISSUE TITLE
Enhancement Request: New-SafeguardAsset to include 'PrivilegeElevationCommand' option

### ISSUE THREAD

**Issue by gilesmarshall** [OneIdentity/safeguard-ps#201]
When creating a new Linux asset using`New-SafeguardAsset` , most of the Connection Properties can be defined - but not "PrivilegeElevationCommand" which seems to be a bit of an omission.

I am successfully updating this attribute following asset creation by using `Invoke-SafeguardMethod` but it would be nice to do it at creation time.

From what I can see it would be a simple modification to assets.psm1 :-)

Thanks

**Comment by petrsnd** [comment]
This can be easily changed.  I'll put it in before we officially release for 2.10.

**Comment by gilesmarshall** [comment]
@petrsnd 
Brilliant, thanks

**Comment by petrsnd** [comment]
Fixed in #203
