### ISSUE TITLE
using Get-SafeguardUser example

### ISSUE THREAD

**Issue by walkerpauldavid** [OneIdentity/safeguard-ps#21]
Hi there, on the home page to this project there's an example of calling Get-safeguardUser XXXX where XXXX is the username. When I try this exactly as shown in the welcome notes I responds with Invalid filter. just saying maybe the example needs updating?
```Powershell
PS C:\Windows\system32> Get-SafeguardUser Admin
Invoke-RestMethod : {"Code":70011,"Message":"Invalid filter - expression must evaluate to a boolean.","InnerError":null}
At C:\Users\pwalker\Documents\WindowsPowerShell\Modules\safeguard-ps\2.1.0.50\safeguard-ps.psm1:206 char:13
+             Invoke-RestMethod -Method $Method -Headers $Headers -Uri  ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

**Comment by DanPeterson** [comment]
Hey @walkerpauldavid 
I'm assuming you've already properly authenticated using Connect-Safeguard.
It works for me.  Let's get some info about your host to see what's different from mine.
Run the following commands for me and get me the output:
```Powershell
> Get-Module safeguard-ps | fl
```
```Powershell
> Get-Host
```
```Powershell
> $PSVersionTable
```

**Comment by walkerpauldavid** [comment]
Hey Dan, thanks for the prompt reply, yes I was correct authenticated.. here's the output:

```
> PS C:\Windows\system32> Get-Module safeguard-ps | fl
> 
> 
> Name              : safeguard-ps
> Path              : C:\Users\pwalker\Documents\WindowsPowerShell\Modules\safeguard-ps\2.1.0.50\safeguard-ps.psm1
> Description       : Scripting tools for interacting with the One Identity Safeguard Web API.
> ModuleType        : Script
> Version           : 2.1.0.50
> NestedModules     : {sslhandling, ps-utilities, sg-utilities, datatypes...}
> ExportedFunctions : {Clear-SafeguardSslCertificateForAppliance, Connect-Safeguard, Disable-SafeguardUser, Disconnect-Safeguard...}
> ExportedCmdlets   :
> ExportedVariables :
> ExportedAliases   :

PS C:\Windows\system32> Get-Host


Name             : ConsoleHost
Version          : 5.1.14393.1770
InstanceId       : 32666266-e93f-4cc7-a876-49201aff7a38
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-GB
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

PS C:\Windows\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.1770
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1770
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
``

**Comment by DanPeterson** [comment]
Can you grab the information for that last command I added?

```Powershell
> [System.Environment]::OSVersion.Version
```

**Comment by DanPeterson** [comment]
Also, can you dump your session variable.  I don't really need the token so you can leave that out if you want, but the output would be truncated anyway.
```Powershell
> $SafeguardSession
```

**Comment by walkerpauldavid** [comment]
apologies it's late here and I forgot that one

`PS` C:\Windows\system32> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  `0`

PS C:\Windows\system32> $SafeguardSession

Name                           Value
----                           -----
Appliance                      10.10.XX.XX
Thumbprint
Username                       Admin
Version                        2
Insecure                       True
AccessToken                    XXXXXXXXXXXXXXXXXzhfNE1Zcmt1NCJ9.eyJBY3R1YWxVc2VySWQiOiItMiI...
CertificateFile
Gui                            False
IdentityProvider               local

**Comment by walkerpauldavid** [comment]
.... just to add... Get-Safeguarduser with no parameters works fine..

**Comment by DanPeterson** [comment]
Try:
```Powershell
> Get-SafeguardUser -2
```

**Comment by DanPeterson** [comment]
I think the problem might be in resolving the UserId.  So try:
```Powershell
> Invoke-SafeguardMethod Core GET Users -Parameters @{ filter = "UserName ieq 'Admin'" }
```
and
```Powershell
> Invoke-SafeguardMethod Core GET Users/-2
```

**Comment by walkerpauldavid** [comment]
> Get-SafeguardUser -2

worked Dan.

> Invoke-SafeguardMethod Core GET Users -Parameters @{ filter = "UserName ieq 'Admin'" }

Didn't work.

Invoke-RestMethod : {"Code":70011,"Message":"Invalid filter - expression must evaluate to a boolean.","InnerError":null}
At C:\Users\pwalker\Documents\WindowsPowerShell\Modules\safeguard-ps\2.1.0.50\safeguard-ps.psm1:206 char:13
+             Invoke-RestMethod -Method $Method -Headers $Headers -Uri  ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

> Invoke-SafeguardMethod Core GET Users/-2

Worked.

**Comment by DanPeterson** [comment]
This shouldn't be the problem, but I'm worried it is.  Try this...
```Powershell
> Invoke-SafeguardMethod Core GET Users -Parameters @{ filter = "UserName%20ieq%20'Admin'" }
```

**Comment by walkerpauldavid** [comment]
ah the old white space.... well didn't help, please see below

```
PS C:\Windows\system32> Invoke-SafeguardMethod Core GET Users -Parameters @{ filter = "UserName%20ieq%20'Admin'" }
Invoke-RestMethod : {"Code":70011,"Message":"Invalid filter - expression must evaluate to a boolean.","InnerError":null}
```

**Comment by DanPeterson** [comment]
Ah! I know what it is. You’re talking to Safeguard 2.0.1. We added the ieq operator in 2.1.0 for caseless comparison. I’ll make it a little more backwards compatible.

**Comment by petrsnd** [comment]
This will take a minute to build via appveyor and then you should be able to get the change from update-module cmdlet.  Give it about 30 minutes to be sure.

**Comment by DanPeterson** [comment]
I forgot to mark this fixed a couple weeks ago.  Make sure you have the latest version.
