### ISSUE TITLE
Enhancement Request: Test-SafeguardAsset - return detailed error information back to calling process

### ISSUE THREAD

**Issue by gilesmarshall** [OneIdentity/safeguard-ps#214]
Hi,

When an error occurs with `Test-SafeguardAsset`, the cmdlet returns a simple message "`Task Completed with Failure`", with no further detail as to the reason for the failure, especially when compared to information available for the same operation using the Safeguard UI.

I see that the function `Wait-LonrunningTask` actually produces quite detailed information in `$Taskresponse.Log` as shown below:

`Timestamp                Status     Message `                                                      
`---------                ------     -------`
`2019-11-26T11:05:42.999Z Queued     Queuing task.`
`2019-11-26T11:05:43Z     Running    Starting task.`
`2019-11-26T11:05:43.113Z Connecting Connecting with asset SERVER1 (10.0.0.1).`
`2019-11-26T11:05:43.461Z Checking   System login test.`
`2019-11-26T11:05:44.103Z Checking   Testing connection to asset SERVER1 using address 10.0.0.1.`
`2019-11-26T11:05:44.365Z Checking   Insufficient Privileges to access the password information.`     
`2019-11-26T11:05:44.366Z Finalizing System connection test failed.`
`2019-11-26T11:05:44.375Z Saving     Saving task results.`
`2019-11-26T11:05:44.376Z Failure    Task completed with failure.`

Could this information be (optionally?) passed back to the the calling process as an object for further actions and analysis if required?  The detail I would like from this example is `Insufficient Privileges to access the password information.` instead of just the failure.

Thanks for your great work on these modules.

Giles

**Comment by petrsnd** [comment]
Fixed in 2.11

**Comment by gilesmarshall** [comment]
Thanks petrsnd, 

I've been able to test this and my only comment is that the error detail seems to be returned as a single string rather than an object that can be manipulated.
`$Error[0].Exception.Message` contains the text:

`Task completed with failure.`
` 2019-12-20T11:41:06.346Z   Queued       Queuing task.`
` 2019-12-20T11:41:06.347Z   Running      Starting task.`
` 2019-12-20T11:41:06.451Z   Connecting   Connecting with asset Server01 (10.0.0.1).`
` 2019-12-20T11:41:27.457Z   Connecting   Connecting to asset Server01 (10.0.0.1) failed with error: Connection timed out..`
` 2019-12-20T11:41:27.458Z   Finalizing   System connection test failed.`
` 2019-12-20T11:41:27.473Z   Saving       Saving task results.`
` 2019-12-20T11:41:27.474Z   Failure      Task completed with failure.`

And there is no simple way to acess either the first line summary `Task completed with failure.` or perhaps to loop through each output.

Something for future consideration...
Thanks

**Comment by petrsnd** [comment]
@gilesmarshall 

I changed this to be a strongly typed exception.  Use $Error[0].Exception.TaskLog which will contain an array of objects with timestamp, status, message.
