### ISSUE TITLE
Need better error for TLS certificate validation 

### ISSUE THREAD

**Issue by petrsnm** [OneIdentity/safeguard-ps#255]
Took me way to long to learn that I needed to use -Insecure in order to  use the safeguard cmdlets on a machine without the the CA cert installed. More descriptive error message would have helped a lot.

**Comment by petrsnd** [comment]
This will be fixed in the next release of safeguard-ps which is 6.6.xxx.  It is available immediately in pre-release.

**Comment by petrsnd** [comment]
![image (2)](https://user-images.githubusercontent.com/3847897/80567997-68e1c800-89b3-11ea-9f10-47f2e52e393e.png)
