### ISSUE TITLE
Active Directory Certificate Authentication

### ISSUE THREAD

**Issue by Kevin-Andrew** [OneIdentity/safeguard-ps#261]
When attempting to authenticate using a client certificate by specifying some other provider with the `-IdentityProvider` parameter, Safeguard-ps always defaults to just using the built-in **Certificate** provider.  For example, specifying the following command:
```
Connect-Safeguard 172.21.21.4 -Verbose -IdentityProvider ad5 -Thumbprint "839c7891aad808c4745b4fa648adbf02f6bb86d8"
```
results in having in the log:
```
2020-06-04T16:49:18.038Z [Error] Event:		Access token generation authentication failure
Details:

User Name:	
Action:		certificate:client_credentials
Origin:		172.21.21.10:49934
STS Server:	172.21.21.4:443
Raw URL:	https://172.21.21.4:443/RSTS/oauth2/token
```

The line:
```
Action:		certificate:client_credentials
```
indicates the actual provider ID being used, in this case **certificate**.

If we compare that to a success login attempt using an Active Directory provider, we would see:
```
2020-06-04T16:47:55.378Z [Information] (Pangaea.Service.Rsts ) {RstsLogTraceListener} Event:		Access token generation authentication success:
User Name:	ONE\bruth
Action:		ad5:cert
Origin:		172.21.21.10:49934
STS Server:	172.21.21.4:443
Raw URL:	https://172.21.21.4:443/RSTS/oauth2/token
```

Note the line:
```
Action:		ad5:cert
```
indicating that provider **ad5** was used and the user authenticated with a client certificate (the **cert** part after the provider ID), as opposed to say a username/password.

**Comment by petrsnd** [comment]
Fixed by #262
