### ISSUE TITLE
Edit-SafeguardDirectory always gives error

### ISSUE THREAD

**Issue by JeffHarkavy** [OneIdentity/safeguard-ps#275]
No matter what's passed it always returns the following:

400: Bad Request -- 70000: The request is invalid. entity.AssetPartitionId: The field AssetPartitionId must be a valid non-zero database ID.

**Comment by petrsnd** [comment]
This was likely broken in the refactor to support Enter-SafeguardAssetPartition.

**Comment by petrsnd** [comment]
@Goelrachit

**Comment by Goelrachit** [comment]
Fixed in 6.8.568-pre.

**Comment by Goelrachit** [comment]
@JeffHarkavy please verify this in the latest 6.8 prerelease. Thanks!

**Comment by petrsnd** [comment]
verified that I can change the description of a AD directory asset
