### ISSUE TITLE
Edit-SafeguardDynamicAccountGroup always returns an error

### ISSUE THREAD

**Issue by JeffHarkavy** [OneIdentity/safeguard-ps#276]
Even when -GroupingRule is supplied it always returns "Cannot bind argument to parameter 'Rule' because it is null."  The same grouping rule works correctly with Add-SafeguardDynamicAccountGroup

**Comment by petrsnd** [comment]
@Goelrachit

**Comment by Goelrachit** [comment]
Fixed in 6.8.568-pre.

**Comment by Goelrachit** [comment]
@JeffHarkavy please verify this in the latest 6.8 prerelease. Thanks!

**Comment by petrsnd** [comment]
fixed, but I found a bug with a few missing attributes for grouping rules
