### ISSUE TITLE
Find-SafeguardDirectoryAccount never returns anything

### ISSUE THREAD

**Issue by JeffHarkavy** [OneIdentity/safeguard-ps#277]
Get-SafeguardDirectoryAccount -DirectoryToGet jshdevvm.dell.com -AccountToGet User_001 returns an object

These all return nothing
Find-SafeguardDirectoryAccount "User"
Find-SafeguardDirectoryAccount -SearchString "User_001"
Find-SafeguardDirectoryAccount -QueryString "DirectoryProperties.DomainName eq 'jshdevvm.dell.com'"
Find-SafeguardDirectoryAccount -QueryString "Name eq 'User_001'"

**Comment by petrsnd** [comment]
I'll have to look to see if this is fixable.  The DirectoryAccount cmdlets will probably eventually be deprecated.

**Comment by Goelrachit** [comment]
Fixed in 6.8.568-pre.

**Comment by Goelrachit** [comment]
@JeffHarkavy please verify this in the latest 6.8 prerelease. Thanks!

**Comment by petrsnd** [comment]
This is fixed, but I noticed the `-Fields` is broken for this cmdlet.
