### ISSUE TITLE
Edit-SafeguardDynamicAccountGroup and Edit-SafeguardDynamicAssetGroup parameter names

### ISSUE THREAD

**Issue by JeffHarkavy** [OneIdentity/safeguard-ps#279]
Edit-SafeguardDynamicAccountGroup and Edit-SafeguardDynamicAssetGroup both use `-GroupToGet` as opposed to `-GroupToEdit`. 

Other Edit-Safeguard* commands use `-ThingToEdit` form.  Consistency?

**Comment by Goelrachit** [comment]
Fixed in 6.8.568-pre. Changed the parameter name to -GroupToGet.

**Comment by Goelrachit** [comment]
@JeffHarkavy please verify this in the latest 6.8 prerelease. Thanks!

**Comment by petrsnd** [comment]
Fixed
