### ISSUE TITLE
Wait-SafeguardApplianceStateOnline with -timeout < 10 returns unexpected error

### ISSUE THREAD

**Issue by JeffHarkavy** [OneIdentity/safeguard-ps#281]
appliance *is* online when called

Wait-SafeguardApplianceStateOnline -Timeout 9
Cannot validate argument on parameter 'PercentComplete'. The 111 argument is greater than the maximum allowed range of 100. Supply an argument that is less than or equal to 100 and then try the command again.
At C:\Program Files\WindowsPowerShell\Modules\safeguard-ps\6.7.551\sg-utilities.psm1:280 char:5

Wait-SafeguardApplianceStateOnline -Timeout 10
Safeguard is back online.

It does not seem to be timeout related since -Timeout 10 returns in ~7 seconds

**Comment by petrsnd** [comment]
This cmdlet doesn't have precision that allows for less than 10 sec waits to be accurate.  If the caller specified < 10 we are going to just round up to 10.  That's close to the initial polling interval right now anyway.

**Comment by petrsnd** [comment]
Fixed in 6.7.561-pre
