### ISSUE TITLE
Get-SafeguardAccessPolicyScopeItem never returns anything

### ISSUE THREAD

**Issue by JeffHarkavy** [OneIdentity/safeguard-ps#282]
Get-SafeguardAccessPolicyScopeItem -PolicyToGet `policyName` never returns data.  If the policy does not exist it will throw an error, but as long as the policy exists it "succeeds" with nothing returned

**Comment by petrsnd** [comment]
I think this might have been committed partially implemented.

**Comment by Goelrachit** [comment]
It appears to be working fine:

![image](https://user-images.githubusercontent.com/9425386/94193672-7c5f6500-fe65-11ea-8d0c-750c1acfc9ca.png)

**Comment by Kevin-Andrew** [comment]
This appears to be working for me with version [6.8.578-pre](https://www.powershellgallery.com/packages/safeguard-ps/6.8.578-pre).
