### ISSUE TITLE
Import-SafeguardBackup does not accept any relative path for -BackupFile

### ISSUE THREAD

**Issue by JeffHarkavy** [OneIdentity/safeguard-ps#283]
`-BackupFile "c:\workdirectory\backups\cmdlet-test-sgbackup_20200818_130450.sgb"` works fine
`-BackupFile ".\backups\cmdlet-test-sgbackup_20200818_130450.sgb"` does not

Unless you supply an absolute path for the filename you get 
`Exception calling "ReadAllBytes" with "1" argument(s): "Could not find a part of the path 'C:\WINDOWS\system32\backups\cmdlet-test-sgbackup_20200818_130450.sgb'."`

Either fix the `C:\WINDOWS\system32` part or put the need for the full, absolute path in teh command description

**Comment by petrsnd** [comment]
Fixed in 6.7.559-pre
