### ISSUE TITLE
Save-SafeguardBackupToArchive description is the same as Remove-SafeguardBackup

### ISSUE THREAD

**Issue by JeffHarkavy** [OneIdentity/safeguard-ps#284]
Evil clipboard strikes again

**Comment by petrsnd** [comment]
@Goelrachit

**Comment by Goelrachit** [comment]
Fixed in 6.8.568-pre

**Comment by Goelrachit** [comment]
@JeffHarkavy please verify this in the latest 6.8 prerelease. Thanks!

**Comment by Kevin-Andrew** [comment]
This appears fixed in [6.8.578-pre](https://www.powershellgallery.com/packages/safeguard-ps/6.8.578-pre).
