### ISSUE TITLE
Get-SafeguardSupportBundle -OutFile does not accept partial or relative paths

### ISSUE THREAD

**Issue by JeffHarkavy** [OneIdentity/safeguard-ps#285]
These work
`Get-SafeguardSupportBundle -OutFile foo.zip`
`Get-SafeguardSupportBundle -OutFile c:\somedirectory\subdirectory\foo.zip`

This does not
`Get-SafeguardSupportBundle -OutFile .\subdirectory\foo.zip`

returns the following exception

`An exception occurred during a WebClient request.`
`At C:\Program Files\WindowsPowerShell\Modules\safeguard-ps\6.7.551\sg-utilities.psm1:135 char:5`
`+     throw $local:ExceptionToThrow`
`+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : OperationStopped: (:) [], WebException`
`    + FullyQualifiedErrorId : An exception occurred during a WebClient request.`

**Comment by petrsnd** [comment]
Fixed in 6.7.557-pre
