### ISSUE TITLE
Get-SafeguardDeletedUser -UserToGet "someUserName" returns error if > 1 user matches

### ISSUE THREAD

**Issue by JeffHarkavy** [OneIdentity/safeguard-ps#286]
Applies to Get-SafeguardDeletedUser, Get-SafeguardDeletedAsset, and Get-SafeguardDeletedAssetAccount

Get-SafeguardDeleted_thing_ <no arguments>
- returns entire list

Get-SafeguardDeleted_thing_ somename
- returns `Found XX _things_ matching 'somename' in deleted _things_`

Why not just return the list of things that match?

**Comment by Goelrachit** [comment]
With the -ThingToGet parameter, we expect to return the exact object that match this name or Id. If an Id is passed in as the -ThinkToGet argument, it will always return only one object.  This is consistent with other similar cmdlets like Get-SafeguardAsset -AssetToGet and Get-SafeguardAssetAccount -AccountToGet.

My concern is that changing this behavior might affect how Identity Manager  or other customers use these cmdlets and any automation they might have that expects error or a single object. I think we should not make this change unless requested by a customer.

The work around to get all the matching object is to get all the objects and filter by name:

(Get-SafeguardAssetAccount) | where {$_.Name -match 'accountname'}

**Comment by petrsnd** [comment]
Working as designed
