### ISSUE TITLE
Connect-Safeguard returns Access Denied on *nix systems

### ISSUE THREAD

**Issue by dyzcypul** [OneIdentity/safeguard-ps#288]
The `Auto` in `PtrToStringAuto()` means that the unmanaged input string is assumed to use a _platform-appropriate_ character encoding, whereas `BSTR` is
a "Unicode" (UTF-16) string on _all_ platforms. **On Windows, an unmanaged string is assumed to have UTF-16 encoding (which is why the code works), whereas on Unix-like platforms it is UTF-8.** 

https://github.com/PowerShell/PowerShell/issues/11953

The fix would be to replace `PtrToStringAuto()` with `PtrToStringBSTR()`

**Comment by petrsnd** [comment]
It was working, but there have been some updates recently from other team members who might not have tested them on Linux or Mac.

**Comment by petrsnd** [comment]
@dyzcypul Fixed in 6.7.555-pre.  The official 6.7 release will probably be out tomorrow.
