### ISSUE TITLE
Get-SafeguardA2aPrivateKey using the wrong value for CredentialType (Key vs PrivateKey)

### ISSUE THREAD

**Issue by robertlbyrne** [OneIdentity/safeguard-ps#297]
Error looks like: 'Key' is not valid for A2ACredentialType

Noticed this in: v6.7.563 of safeguard-ps.

Simple workaround for the moment is to modify the Invoke-SafeguardA2aCredentialRetrieval function to transform Key to PrivateKey. Also need to add PrivateKey to the ValidateSet of $CredentialType in the signature.

switch ($CredentialType)
{
"password" { $CredentialType = "Password"; break }
"key" { $CredentialType = "PrivateKey"; break }
}

**Comment by petrsnd** [comment]
This is fixed in https://www.powershellgallery.com/packages/safeguard-ps/6.7.575

**Comment by petrsnd** [comment]
You should be able to use Update-Module to get the new working cmdlets.
