### ISSUE TITLE
Update Asset Account Password

### ISSUE THREAD

**Issue by cmatamr** [OneIdentity/safeguard-ps#334]
I'm trying to set the Account password. 

When invoke the method from powershell I get this error...
400: Bad Request -- 70000: The request is invalid. entity.: Unexpected character encountered while parsing value: [. Path '', line 1, position 1.

I have tried these two ways...

1.Invoke-SafeguardMethod Core PUT "AssetAccounts/$($AccountId)/Password" -Body @(@{
    
    "password" = "$Password"

})

2.Invoke-SafeguardMethod Core PUT "AssetAccounts/$($AccountId)/Password" -JsonBody "{
    
    `"password`" : `"$Password`"
}"

But always get the same result.. 400:Bad Request..

I don't know where the error is...

**Comment by MichaelThompson** [comment]
The json body should just be "$Password" -- it is expecting just a string

**Comment by petrsnd** [comment]
@cmatamr I would recommend using `Set-SafeguardAssetAccountPassword`, which is a purpose-built cmdlet for this operation.

You can see what cmdlets are available using `Get-SafeguardCommand`.  For example, `Get-SafeguardCommand set password`.

If you want to call the endpoint directly using `Invoke-SafeguardMethod`, you need to follow the instructions provided by @MichaelThompson.  You can see the implementation in the source code here: https://github.com/OneIdentity/safeguard-ps/blob/f9b84de40d5c4eafd6465017ddf1f8a902889003/src/assets.psm1#L1744
