### ISSUE TITLE
Set-SafeguardDiagnosticPackage fails with HTTP 415: Unsupported Media Type

### ISSUE THREAD

**Issue by aamburn** [OneIdentity/safeguard-ps#342]
The Set-SafeguardDiagnosticPackage cmdlet fails against a 6.10 Safeguard Appliance with the error above. 

Workaround is to use 

_invoke-safeguardmethod appliance post "DiagnosticPackages" <path> -ContentType "application/octet-stream"_

**Comment by petrsnd** [comment]
Fixed by #343

**Comment by petrsnd** [comment]
Forgot to close this issue.  The fix will be in 6.11 release.
