### ISSUE TITLE
Support Events Subscription for Events with no ObjectType in New-SafeguardEventNotification

### ISSUE THREAD

**Issue by kcy43ccwc** [OneIdentity/safeguard-ps#349]
Currently New-SafeguardEventNotification only allows a limited set (Asset, AssetAccount and DirectoryAccount) event as input parameter. Would request to include the rest of events where some of them does not have ObjectType to be used as input for this cmdlet (example, ApplianceBackupStarted and ApplianceBackupCompleted event). The workaround currently is to use Invoke-SafeguardMethod to post to EventSubscription for these subscription creation. 

A short discussion on the matter below: 
https://connect.oneidentity.com/products/privileged-access-management/f/forum/4561/restapi-method-for-creating-event-subscription-for-appliance/14895#14895

**Comment by petrsnd** [comment]
There are some deficiencies with the event subscription cmdlets.  Those will be corrected in an upcoming release.

**Comment by petrsnd** [comment]
@kcy43ccwc We reworked the event subscription cmdlets in #374.  That code is available in safeguard-ps 6.13.  Can you let me know if it works for your use case?

**Comment by kcy43ccwc** [comment]
> @kcy43ccwc We reworked the event subscription cmdlets in #374. That code is available in safeguard-ps 6.13. Can you let me know if it works for your use case?

This is working now, i'm able to subscribe to event without objectype restriction. Thanks!
