### ISSUE TITLE
Issue with Invoke-SafeguardAssetAccountPasswordChange cmdlet on Powershell 7.x

### ISSUE THREAD

**Issue by kcy43ccwc** [OneIdentity/safeguard-ps#384]
Mentioned cmdlet works on Powershell 5.1 but not able to run properly on Powershell 7.2.1. In Powershell 7.2.1, it throws error when it is being executed. Error message --> "Invoke-RestMethod: Cannot convert 'System.String[]' to the type 'System.Uri' required by parameter 'Uri'. Specified method is not supported." Suspect this has something to do with this thread: https://github.com/PowerShell/PowerShell/issues/15039

**Comment by petrsnd** [comment]
@kcy43ccwc What version of safeguard-ps are you using?

It is working for me on 7.2.4.
![image](https://user-images.githubusercontent.com/3847897/172263355-7930647f-5f81-40e5-9908-44fe80a26d71.png)

**Comment by kcy43ccwc** [comment]
@petrsnd Just did some testing since your reply, it's not the powershell version that is causing the problem. Instead, its the safeguard-ps version. I'm on Powershell 7.2.4 and issue persist with safeguard-ps 6.13.50277, however after installing safeguard-ps 7.0.59331-pre, it ran successfully. 

On my earlier successful attempt, it was running on safeguard-ps 6.0.x with powershell. Hence, looks like this issue is happening on safeguard-ps 6.13.50277.

**Comment by petrsnd** [comment]
@kcy43ccwc I was able to reproduce this in 6.13.  I'll see if I can find the update that fixes it in 7.0 and backport it to 6.13.

**Comment by petrsnd** [comment]
Fixed in https://www.powershellgallery.com/packages/safeguard-ps/6.13.62645

**Comment by kcy43ccwc** [comment]
> Fixed in https://www.powershellgallery.com/packages/safeguard-ps/6.13.62645
Got it, thanks!
