### ISSUE TITLE
Get-SafeguardDnsSuffix not working in 7.0.59130

### ISSUE THREAD

**Issue by miroberts** [OneIdentity/safeguard-ps#389]
Using Jeff's tool here  https://github.com/JeffHarkavy/SafeguardCmdletTesting  I got this to pass on 6.13 and now upgraded to 7.0 it doesn't
--------------------------------------------------
-- Get-SafeguardDnsSuffix
--------------------------------------------------
Get-SafeguardDnsSuffix : Unepxected error - L:165 406: Not Acceptable -- 60379: This action is no longer available in this version.

**Comment by petrsnd** [comment]
Accounted for an API change
