### ISSUE TITLE
SafeguardDirectory not working in 7.0.59130 

### ISSUE THREAD

**Issue by miroberts** [OneIdentity/safeguard-ps#393]
Using Jeff's tool here https://github.com/JeffHarkavy/SafeguardCmdletTesting I got this to pass on 6.13 and now upgraded to 7.0.59130 it doesn't

+==========================================================================+
|                       BEGIN Running Directory Tests                      |
| 06-07-2022 18:33:17.910                                                  |
| Expected: 22                                                             |
+==========================================================================+
Set-SafeguardNetworkInterface : 10.9.6.64 already present in X0 DNS list
Get-SafeguardAccountPasswordRule : Macrocosm Password Rule has Min=10 Max=20 characters
Get-SafeguardDirectoryMigrationData : Unexpected error getting getting migration data on 10.5.34.128 - L:165 400: Bad Request -- 70010: Invalid filter - enum
value is not defined: DirectoryCreated.
New-SafeguardDirectory : c.sg.lab successfully created
Edit-SafeguardDirectory : Edit failed
Task completed successfully.
 2022-06-07T18:33:27.192Z   Queued       Queuing task.
 2022-06-07T18:33:27.201Z   Running      Starting task.
 2022-06-07T18:33:27.363Z   Checking     Connecting with directory c.sg.lab on domain controller dc2-c.c.sg.lab.
 2022-06-07T18:33:27.372Z   Connecting   Connecting with asset c.sg.lab (dc2-c.c.sg.lab).
 2022-06-07T18:33:27.505Z   Finalizing   System connection test succeeded.
 2022-06-07T18:33:27.554Z   Saving       Saving task results.
 2022-06-07T18:33:27.684Z   Success      Task completed successfully.

Test-SafeguardDirectory : Successfully called test on directory c.sg.lab
Get-SafeguardDirectoryAccount : Found 1 accounts
Directory general : Unexpected error in Directory test - L:165 400: Bad Request -- 70009: Invalid filter property - 'AssetName' is not a valid filter property
 name.

**Comment by petrsnd** [comment]
@miroberts I can't see what's failing with this one.  What cmdlet is it running?

Get-SafeguardDirectoryAccount is working for me.
Test-SafeguardDirectory and Test-SafeguardDirectoryAccountPassword are working as well.

**Comment by miroberts** [comment]
@petrsnd the only use of AssetName as a filter property I see in that test is this:

`$found = Find-SafeguardAssetAccount -QueryFilter "AssetName eq '$($DATA.domainName)' and Name eq '$acctname'"`

and I don't see anything wrong with that doing it by hand though...

`PS C:\Users\Administrator\Documents\Repo\SafeguardComdletTesting> Find-SafeguardAssetAccount -Insecure -QueryFilter "AssetName eq 'what' and Name eq 'now'"
Appliance: 10.5.34.128
(certificate, local)
Provider: local
Username: sudo
Password: ********
PS C:\Users\Administrator\Documents\Repo\SafeguardComdletTesting>`

However I still see this error now. I will try and track it down more.

**Comment by miroberts** [comment]
Find-SafeguardAssetAccount -Verbose -QueryFilter "AssetName eq 'ps.Asset_001' and Name eq 'psuser_1'" :
VERBOSE: Importing function 'Add-SafeguardAssetPartitionOwner'.
VERBOSE: Importing function 'Edit-SafeguardAssetPartition'.
VERBOSE: Importing function 'Enter-SafeguardAssetPartition'.
VERBOSE: Importing function 'Exit-SafeguardAssetPartition'.
VERBOSE: Importing function 'Get-SafeguardAssetPartition'.
VERBOSE: Importing function 'Get-SafeguardAssetPartitionOwner'.
VERBOSE: Importing function 'Get-SafeguardCurrentAssetPartition'.
VERBOSE: Importing function 'New-SafeguardAssetPartition'.
VERBOSE: Importing function 'Remove-SafeguardAssetPartition'.
VERBOSE: Importing function 'Remove-SafeguardAssetPartitionOwner'.
VERBOSE: Importing function 'Resolve-AssetPartitionIdFromSafeguardSession'.
VERBOSE: Importing function 'Resolve-SafeguardAssetPartitionId'.
VERBOSE: Insecure=True
VERBOSE: Configuring SSL version support to be secure
VERBOSE: Disabling SSL on Windows platform
VERBOSE: Adding the trust everything callback
VERBOSE: ---Request---
VERBOSE: Headers={
    "Accept":  "application/json",
    "Content-type":  "application/json"
}
VERBOSE: Url=https://10.5.34.128/service/core/v4/AssetAccounts?filter=AssetName%20eq%20'ps.Asset_001'%20and%20Name%20eq%20'psuser_1'
VERBOSE: Parameters={
    "filter":  "AssetName eq \u0027ps.Asset_001\u0027 and Name eq \u0027psuser_1\u0027"
}
VERBOSE: GET https://10.5.34.128/service/core/v4/AssetAccounts?filter=AssetName eq 'ps.Asset_001' and Name eq 'psuser_1' with 0-byte payload
VERBOSE: Importing function 'Format-DateTimeAsString'.
VERBOSE: Importing function 'Format-UtcDateTimeAsString'.
VERBOSE: Importing function 'Get-EntireAuditLogStartDateAsString'.
VERBOSE: Importing function 'Get-VpnIpv6Address'.
VERBOSE: Importing function 'New-LongRunningTaskException'.
VERBOSE: Importing function 'Out-SafeguardExceptionIfPossible'.
VERBOSE: Importing function 'Resolve-DomainNameFromIdentityProvider'.
VERBOSE: Importing function 'Resolve-ReasonCodeId'.
VERBOSE: Importing function 'Resolve-SafeguardAccountIdWithAssetId'.
VERBOSE: Importing function 'Resolve-SafeguardAccountIdWithoutAssetId'.
VERBOSE: Importing function 'Resolve-SafeguardAssetId'.
VERBOSE: Importing function 'Test-SafeguardMinVersionInternal'.
VERBOSE: Importing function 'Wait-ForClusterOperation'.
VERBOSE: Importing function 'Wait-ForPatchDistribution'.
VERBOSE: Importing function 'Wait-ForSafeguardOnlineStatus'.
VERBOSE: Importing function 'Wait-ForSafeguardStatus'.
VERBOSE: Importing function 'Wait-ForSessionModuleState'.
VERBOSE: ---Response Status---
VERBOSE: 400 Bad Request
VERBOSE: ---Response Body---
VERBOSE: {"Code":70009,"Message":"Invalid filter property - 'AssetName' is not a valid filter property name.","InnerError":null}
VERBOSE: ---Exception---
VERBOSE:

Status         : ProtocolError
Response       : System.Net.HttpWebResponse
Message        : The remote server returned an error: (400) Bad Request.
Data           : {}
InnerException :
TargetSite     : System.Net.WebResponse GetResponse(System.Net.WebRequest)
StackTrace     :    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
                    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
HelpLink       :
Source         : Microsoft.PowerShell.Commands.Utility
HResult        : -2146233079



VERBOSE: NOT FOUND: YOU MAY BE USING AN OLDER VERSION OF SAFEGUARD API:
VERBOSE:     TRY CONNECTING WITH THE Version PARAMETER SET TO 3, OR
VERBOSE:     DOWNLOAD THE VERSION OF safeguard-ps MATCHING YOUR VERSION OF SAFEGUARD
VERBOSE: Enabling SSL on Windows platform
VERBOSE: Removing the trust everything callback
general : Unexpected error creating Asset Accounts on ps.Asset_001 - L:165 400: Bad Request -- 70009: Invalid filter property - 'AssetName' is not a valid filter property name.

**Comment by petrsnd** [comment]
Updated the test to use the proper attribute name for v4.
