### ISSUE TITLE
Get-SafeguardEventSubscription 500 internal server error in version 7.0.59130

### ISSUE THREAD

**Issue by miroberts** [OneIdentity/safeguard-ps#395]
Using Jeff's tool here https://github.com/JeffHarkavy/SafeguardCmdletTesting I got this to pass on 6.13 and now upgraded to 7.0.59130 it doesn't

+==========================================================================+
|              BEGIN Running Event Subscription Creation Tests             |
| 06-07-2022 18:33:47.220                                                  |
+==========================================================================+
Searching for platforms with 'Ubuntu 20.04 x86_64'
Found  platforms matching 'Ubuntu 20.04 x86_64':
[
    336 - Ubuntu 20.04 x86_64
]
Enter platform ID or search string: 336
New-SafeguardAsset : ps.Asset_001 added for event subscription. Will be removed when done.
New-SafeguardEventSubscription : Successfully created event Subscription Id=75
Edit-SafeguardEventSubscription : Successfully edited event Subscription Description 'Edited subscription description'
Get-SafeguardEventSubscription : Successfully retrieved Subscription Id=75
Event Subscription general : Unexpected error testing Event Subscriptions - L:165 500: Internal Server Error -- 60109: An unexpected LinqException was thrown:
 Expression 'EventSubscriberModel.SnmpAuthenticationPassword' is not a Field..

**Comment by petrsnd** [comment]
@miroberts I think this one is a bug in the test.

**Comment by petrsnd** [comment]
Take note that I overhauled event subscription cmdlets in 6.13.

**Comment by petrsnd** [comment]
This is a bug in the v4 API of SPP.  Bug will be fixed there.
