### ISSUE TITLE
createUser not working in 7.0.59130 

### ISSUE THREAD

**Issue by miroberts** [OneIdentity/safeguard-ps#396]
Using Jeff's tool here https://github.com/JeffHarkavy/SafeguardCmdletTesting I got this to pass on 6.13 and now upgraded to 7.0.59130 it doesn't

+==========================================================================+
|             BEGIN Running Entitlement and Access Policy Tests            |
| 06-07-2022 18:34:04.726                                                  |
+==========================================================================+
createUser : Unexpected error fetching or creating safeguard-ps-user
Entitlement and Access Policy general : Unexpected error in Entitlement and Access Policy test - L:192 400: Bad Request -- 70009: Invalid filter property - 'U
serName' is not a valid filter property name.

**Comment by petrsnd** [comment]
@miroberts This should be fixed with #400
