### ISSUE TITLE
New-SafeguardAccessRequest cmdlet ignores -AccessRequestType parameter (works for 6.x cmdlets)

### ISSUE THREAD

**Issue by holger-weihe** [OneIdentity/safeguard-ps#452]
After update of the safeguard-ps package from version 6 to 7 the cmdlet New-SafeguardAccessRequest does not work anymore. It looks like the cmdlet ignores the -AccessRequestType parameter so if you have an access request policy in Safeguard which gives access for the requested acccount on that asset in example to a password and a session the cmdlet will find more then one object 
 which will cause an error because the cmdlets expects to find one object only. 

![almauser](https://user-images.githubusercontent.com/94477086/212343670-113ed892-3279-4a4c-86ca-9e4d1d1fe1b7.JPG)

If you run the script attached with the account configured as described you will get something like:

```
PS C:\.....\WindowsPowerShell\Scripts> .\almauser.ps1
Found 3 requestable accounts matching 'almauser'
At C:\Program Files\WindowsPowerShell\Modules\safeguard-ps\7.1.83373\requests.psm1:104 char:13
+             throw "Found $($local:Accounts.Count) requestable account ...
    + CategoryInfo          : OperationStopped: (Found 3 request...hing 'almauser':String) [], RuntimeException
    + FullyQualifiedErrorId : Found 3 requestable accounts matching 'almauser'
```
   
[almauser.ps1.txt](https://github.com/OneIdentity/safeguard-ps/files/10412284/almauser.ps1.txt)

**Comment by miroberts** [comment]
There was a change in the Powershell module to use the v4 API and this error was introduced. We will fix this.

**Comment by miroberts** [comment]
Will you please try this fix.
https://github.com/OneIdentity/safeguard-ps/pull/454

**Comment by petrsnd** [comment]
Fixed build may be found here:
https://www.powershellgallery.com/packages/safeguard-ps/7.2.88225-pre

**Comment by petrsnd** [comment]
@holger-weihe Have you been able to verify the fix?

**Comment by holger-weihe** [comment]
@petrsnd Thanks for fixing. Verified and my script now works again.
