### ISSUE TITLE
Connect-Safeguard commandlet fails when using a £ sign - UTF8 encoding error

### ISSUE THREAD

**Issue by PaulJex** [OneIdentity/safeguard-ps#455]
I'm logging on to an SPP node with the v7.2.83376 of the safeguard-ps commandlets. 

When the users login password contains a UK '**£**' sign (for example Password1**£**) the login fails:

Request Error
      _The server encountered an error processing the request. The exception message is 'The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter
RSts.Sts.OAuth2:password. The InnerException message was 'There was an error deserializing the object of type System.String. '�' contains invalid UTF8 bytes.'._

The PS command I'm using is: 
Connect-Safeguard -Insecure 10.x.x.x ad27 username -verbose

If I change the users password to swap the **£** for a **$** the login works fine. 

I'm trying to use AD authentication. This is against SPP v7.1. Tried multiple SPP instances, same issue.

Attached is a print screen showing the error (albeit running from one of the provided Sample scripts).

For what its worth, I can login to the Web UI fine. Seems like an UTF8 encoding issue of some kind between PS and the RSTS I'd imagine.

<img width="1168" alt="Error" src="https://user-images.githubusercontent.com/37621831/216068779-4885fec0-ac38-40c8-8f51-b7ae49fcbd4e.png">

**Comment by miroberts** [comment]
Here is a build with this fix in it
https://www.powershellgallery.com/packages/safeguard-ps/7.2.91330-pre

**Comment by PaulJex** [comment]
@miroberts - FYI, tested this against v7.2.91330 and all is working well. Thank you for fixing so quickly.
