### ISSUE TITLE
Get-SafeguardStatus failing with v0 end point when calls using the CmdletBinding

### ISSUE THREAD

**Issue by PaulJex** [OneIdentity/safeguard-ps#457]
I'm using the Sample code >>  [simulate-webui-login.ps1](https://github.com/OneIdentity/safeguard-ps/blob/master/samples/simulate-webui-login.ps1) as the foundation to create a simple script.

When I use the **Get-SafeguardStatus**  in a simple script it works and calls the v4 status endpoint as expected.  
i..e 

/service/notification/**v4**/Status

However,  if I pass all the parameters on the command line using the **CmdletBinding** per the example in the the Samples code, it fails because it uses a v0 end point.

i.e.:
/service/notification/**v0**/Status

The call to this end point fails with http error:
"406: Not Acceptable -- 60379: This action is no longer available in this version."

I'm not specifying which end point version to use, so not sure why its defaulting to the v0?

Tested on multiple workstations (Windows 11 and Windows 10)  with v7.2 PS and the v7.1 PS. 

I can't tell if I'm doing something wrong, but my suspicion is something is not being passed correctly and we default to the v0  end point. The Sample script also fails in the same way.

Print screens showing the issue and the sample script in .txt format.

<img width="781" alt="PS Issue - Working" src="https://user-images.githubusercontent.com/37621831/216308524-88311df6-c918-4c32-ad71-78516111389f.png">

<img width="1030" alt="PS Issue - Failed" src="https://user-images.githubusercontent.com/37621831/216308554-bcdb85ad-259b-4e9a-b107-36e0e3d1f6f1.png">

[failing script example.txt](https://github.com/OneIdentity/safeguard-ps/files/10568221/failing.script.example.txt)

**Comment by petrsnd** [comment]
This cmdlet was deprecated in favor of another, so it was never updated.  However, it is often used in existing scripts, so we probably will never remove it.  The default version number is now applied properly.
