### ISSUE TITLE
New-SafeguardAccessRequest - Unable to specify a custom duration for Access request (uses default value)

### ISSUE THREAD

**Issue by baffledmystic** [OneIdentity/safeguard-ps#465]
Hi,
The New-SafeguardAccessRequest cmdlet doesn't have a parameter to specify duration of the access request.

We've setup the policy to default to 2 hours but allow a longer duration.
When using the PS cmdlet, we aren't able to specify the custom longer duration. Seems there's no parameter available for it.

Please help fix add a parameter for duration.

We are using version 7.0.68972 of the safeguard-ps module.

Thanks!
Shounak S.
IKEA IT AB

**Comment by miroberts** [comment]
@baffledmystic This build has this fix
https://www.powershellgallery.com/packages/safeguard-ps/7.2.92797-pre
Please close this if that resolves your issue.
