### ISSUE TITLE
Edit-SafeguardAsset

### ISSUE THREAD

**Issue by imdroc** [OneIdentity/safeguard-ps#474]
Hi, we can't add a service account to an asset using edit-safeguardasset. we are always getting the same error.
String:
Edit-SafeguardAsset -AssetToEdit ******** -ServiceAccountCredentialType DirectoryPassword -ServiceAccountDomainName ******** -ServiceAccountName ********
Error:
+ FullyQualifiedErrorId : 400: Bad Request -- 60202: A valid service account must be specified for this connection type.

We know that the service account that we are using is correct. It's a domian account onboarded already into SPP

**Comment by petrsnd** [comment]
@imdroc We will try to reproduce this and get back to you.

**Comment by imdroc** [comment]
Hi @petrsnd any news? we still can't add the service accounts to the assets

**Comment by petrsnd** [comment]
@imdroc I have reproduced. The error you are seeing is coming back from SPP. I need to investigate further, because I think the request safeguard-ps is sending is wrong.

**Comment by petrsnd** [comment]
@imdroc This looks like an error in the safeguard-ps module. When you edit to set a directory account connection type you have to set the `ConnectionProperties.ServiceAccountId` property to a valid ID.  Currently, the cmdlet is only setting `ConnectionProperties.ServiceAccountDomainName` and `ConnectionProperties.ServiceAccountName`.  I need to fix the cmdlet to work properly, but in the meantime, a workaround would be to look up the account ID and pass it in on the command line.

```PowerShell
PS> Edit-SafeguardAsset -AssetToEdit engdtopw01 -ServiceAccountCredentialType DirectoryPassword -ServiceAccountId 2
```

**Comment by imdroc** [comment]
It worked just fine now. Thanks

**Comment by imdroc** [comment]
It worked just fine now. Thanks
