### ISSUE TITLE
Py-Safeguard issue-- SSL verification failed

### ISSUE THREAD

**Issue by sgundlach3** [OneIdentity/safeguard-ps#482]
We are trying to use Py-Safeguard to call A2A to retrieve a password, but not sure on a few items:

1) Which is the "pathtoca"-- is the CA either the initial  the root certificate created , or the issuing CA certificate?

2) We saw in the PySafeguard notes that encrypted private keys are NOT supported.  We tried decrypting the private key using openssl, but that did not work either-- kept receiving SSL: CERTIFICATE_VERIFY_FAILED

Attached are the testing attempts using Python.

[PY-Safeguard testing for atlasapi_20230516.docx](https://github.com/OneIdentity/safeguard-ps/files/11489691/PY-Safeguard.testing.for.atlasapi_20230516.docx)

Thanks for any help you can offer.

**Comment by Kevin-Andrew** [comment]
> Which is the "pathtoca"-- is the CA either the initial the root certificate created , or the issuing CA certificate?

Are you suggesting that your SSL certificate is a chain consisting of a root CA, an intermediate signing/issuing certificate, and then finally the leaf SSL certificate? For example:
![image](https://github.com/OneIdentity/safeguard-ps/assets/22459191/9533b529-75cc-41dd-91ae-60783de83eaa)

As opposed to a chain consisting of just a root CA and then the leaf SSL certificate, like:
![image](https://github.com/OneIdentity/safeguard-ps/assets/22459191/fd57fe93-feae-43e3-8c81-2e89c0b19c35)

**Comment by petrsnd** [comment]
@sgundlach3 
If you have not found a solution, please reopen this issue under PySafeguard GitHub page:
https://github.com/OneIdentity/PySafeguard/issues
