### ISSUE TITLE
New-SafeguardDynamicAccountGroup cmdlet throws Exception on Powershell 7.3.4

### ISSUE THREAD

**Issue by evetovicsm** [OneIdentity/safeguard-ps#485]
**Environment:**
Powershell: **7.3.4**
safeguard-ps: **7.3.103856**

Running the command:
 **_New-SafeguardDynamicAccountGroup "Linux Servers" "([Platform startswith 'Linux'])"_**
Output:
**_Exception: Conditions string did not parse into three parts [ObjectAttribute CompareType 'CompareValue']: Name match 'root'_**

Running it Powershell 5.1 produces the expected output(The command executes successfully)

**Comment by JeffHarkavy** [comment]
@evetovicsm Thank you for using safeguard-ps.  I have confirmed this issue using either powershell 7.3.4 and 7.3.5 and will investigate further.

**Comment by JeffHarkavy** [comment]
Fix released in safeguard-ps v7.4
