### ISSUE TITLE
apiuser not able to retreive api key with get-a2a-retrievable-account.sh

### ISSUE THREAD

**Issue by sgundlach3** [OneIdentity/safeguard-ps#503]
User was running this same script a few weeeks ago withi no issue, nd then when we started testing, he was getting null for the api key.

Here is the script run and results.

We are able to retrieve the apikey with powershell, but the user is running their process on linux so they need to use bash.
How would they update their safeguard-bash or confirm the version they are using?

Attached is the screen print of the error.

[apiuser can't get apikey using get-a2a-retrieveable-accounts.sh_20231103.docx](https://github.com/OneIdentity/safeguard-ps/files/13288972/apiuser.can.t.get.apikey.using.get-a2a-retrieveable-accounts.sh_20231103.docx)

**Comment by bnicholesdell** [comment]
Is this a Safeguard-ps issue or a Safeguard-Bash issue?  If this is a Safeguard-Bash issue, then it should be entered in the Safeguard-Bash project https://github.com/OneIdentity/safeguard-bash .

**Comment by sgundlach3** [comment]
I am closing the issue. Customer was on SPP version 7.0.1 where there were known issues, and now that they have upgraded to 7.0.4, they are now able to retrieve the API key. Thanks for the reference to oen tickts for bash-- will do so going forward.

**Comment by sgundlach3** [comment]
Thanks, Brad.

We did think it was an issue with Safeguard-bash, but found out it was a known issue with  SPP version 7.0.1, and was resolved when Customer patched to 7.0.4.

Going forward, we will enter any similar issues under safeguard-bash as you recommended.
Thanks again.
Sherry Gundlach

[Text  Description automatically generated]

From: Brad Nicholes ***@***.***>
Date: Tuesday, November 7, 2023 at 5:10 PM
To: OneIdentity/safeguard-ps ***@***.***>
Cc: Sherry Gundlach ***@***.***>, Author ***@***.***>
Subject: Re: [OneIdentity/safeguard-ps] apiuser not able to retreive api key with get-a2a-retrievable-account.sh (Issue #503)

Is this a Safeguard-ps issue or a Safeguard-Bash issue? If this is a Safeguard-Bash issue, then it should be entered in the Safeguard-Bash project https://github.com/OneIdentity/safeguard-bash .
